version: "3"
services:
        php:
                build: .
                volumes:
                        - .:/usr/app/
                        - /usr/app/vendor
                ports:
                        - "8000:8000"
                depends_on:
                        - mysql
        mysql:
                image: mysql:5.7.20
                volumes:
                        - "db_data:/var/lib/mysql"
                        - "./mysql/initial_data:/docker-entrypoint-initdb.d"
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=123.456

volumes:
        db_data:
